using static Sokol.SG;
using static Sokol.SG.sg_backend;
using static Sokol.SG.sg_shader_stage;
using static Sokol.SG.sg_uniform_type;
using static Sokol.SG.sg_uniform_layout;
using static Sokol.SG.sg_image_type;
using static Sokol.SG.sg_sampler_type;
using static Sokol.SG.sg_image_sample_type;
using static Sokol.SG.sg_shader_attr_base_type;
using System.Numerics;
using System.Runtime.InteropServices;


using hmm_vec2=System.Numerics.Vector2;
using hmm_vec3=System.Numerics.Vector3;
using hmm_vec4=System.Numerics.Vector4;
using hmm_mat4=System.Numerics.Matrix4x4;


using vec2_t=System.Numerics.Vector2;
using vec3_t=System.Numerics.Vector3;
using vec4_t=System.Numerics.Vector4;
using mat44_t=System.Numerics.Matrix4x4;


namespace cubemap_jpeg_sapp_shader_cs {

public static unsafe class Shaders 
{
    /*
        #version:1# (machine generated, don't edit!)

        Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

        Cmdline:
            sokol-shdc --input shaders/cubemap-jpeg-sapp.glsl --output shaders/compiled/web/cubemap-jpeg-sapp-shader.cs --slang glsl300es -f sokol_csharp

        Overview:
        =========
        Shader program: 'cubemap':
            Get shader desc: cubemap_shader_desc(sg_query_backend());
            Vertex Shader: vs
            Fragment Shader: fs
            Attributes:
                ATTR_cubemap_pos => 0
        Bindings:
            Uniform block 'vs_params':
                C struct: vs_params_t
                Bind slot: UB_vs_params => 0
            Texture 'tex':
                Image type: SG_IMAGETYPE_CUBE
                Sample type: SG_IMAGESAMPLETYPE_FLOAT
                Multisampled: false
                Bind slot: VIEW_tex => 0
            Sampler 'smp':
                Type: SG_SAMPLERTYPE_FILTERING
                Bind slot: SMP_smp => 0
    */
    public const int ATTR_cubemap_pos = 0;
    public const int UB_vs_params = 0;
    public const int VIEW_tex = 0;
    public const int SMP_smp = 0;
    
[StructLayout(LayoutKind.Sequential)]
    public struct vs_params_t {
        public vs_params_t(){}
        public mat44_t mvp;
    };
    /*
        #version 300 es

        uniform vec4 vs_params[4];
        layout(location = 0) in vec4 pos;
        out vec3 uvw;

        void main()
        {
            gl_Position = mat4(vs_params[0], vs_params[1], vs_params[2], vs_params[3]) * pos;
            uvw = normalize(pos.xyz);
        }

    */
    static readonly byte[] vs_source_glsl300es = {
            0x23,    0x76,    0x65,    0x72,    0x73,    0x69,    0x6f,    0x6e,    0x20,    0x33,    0x30,    0x30,    0x20,    0x65,    0x73,    0x0a,    
            0x0a,    0x75,    0x6e,    0x69,    0x66,    0x6f,    0x72,    0x6d,    0x20,    0x76,    0x65,    0x63,    0x34,    0x20,    0x76,    0x73,    
            0x5f,    0x70,    0x61,    0x72,    0x61,    0x6d,    0x73,    0x5b,    0x34,    0x5d,    0x3b,    0x0a,    0x6c,    0x61,    0x79,    0x6f,    
            0x75,    0x74,    0x28,    0x6c,    0x6f,    0x63,    0x61,    0x74,    0x69,    0x6f,    0x6e,    0x20,    0x3d,    0x20,    0x30,    0x29,    
            0x20,    0x69,    0x6e,    0x20,    0x76,    0x65,    0x63,    0x34,    0x20,    0x70,    0x6f,    0x73,    0x3b,    0x0a,    0x6f,    0x75,    
            0x74,    0x20,    0x76,    0x65,    0x63,    0x33,    0x20,    0x75,    0x76,    0x77,    0x3b,    0x0a,    0x0a,    0x76,    0x6f,    0x69,    
            0x64,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x28,    0x29,    0x0a,    0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x67,    
            0x6c,    0x5f,    0x50,    0x6f,    0x73,    0x69,    0x74,    0x69,    0x6f,    0x6e,    0x20,    0x3d,    0x20,    0x6d,    0x61,    0x74,    
            0x34,    0x28,    0x76,    0x73,    0x5f,    0x70,    0x61,    0x72,    0x61,    0x6d,    0x73,    0x5b,    0x30,    0x5d,    0x2c,    0x20,    
            0x76,    0x73,    0x5f,    0x70,    0x61,    0x72,    0x61,    0x6d,    0x73,    0x5b,    0x31,    0x5d,    0x2c,    0x20,    0x76,    0x73,    
            0x5f,    0x70,    0x61,    0x72,    0x61,    0x6d,    0x73,    0x5b,    0x32,    0x5d,    0x2c,    0x20,    0x76,    0x73,    0x5f,    0x70,    
            0x61,    0x72,    0x61,    0x6d,    0x73,    0x5b,    0x33,    0x5d,    0x29,    0x20,    0x2a,    0x20,    0x70,    0x6f,    0x73,    0x3b,    
            0x0a,    0x20,    0x20,    0x20,    0x20,    0x75,    0x76,    0x77,    0x20,    0x3d,    0x20,    0x6e,    0x6f,    0x72,    0x6d,    0x61,    
            0x6c,    0x69,    0x7a,    0x65,    0x28,    0x70,    0x6f,    0x73,    0x2e,    0x78,    0x79,    0x7a,    0x29,    0x3b,    0x0a,    0x7d,    
            0x0a,    0x0a,    0x00,    
};
    /*
        #version 300 es
        precision mediump float;
        precision highp int;

        uniform highp samplerCube tex_smp;

        layout(location = 0) out highp vec4 frag_color;
        in highp vec3 uvw;

        void main()
        {
            frag_color = texture(tex_smp, uvw);
        }

    */
    static readonly byte[] fs_source_glsl300es = {
            0x23,    0x76,    0x65,    0x72,    0x73,    0x69,    0x6f,    0x6e,    0x20,    0x33,    0x30,    0x30,    0x20,    0x65,    0x73,    0x0a,    
            0x70,    0x72,    0x65,    0x63,    0x69,    0x73,    0x69,    0x6f,    0x6e,    0x20,    0x6d,    0x65,    0x64,    0x69,    0x75,    0x6d,    
            0x70,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x3b,    0x0a,    0x70,    0x72,    0x65,    0x63,    0x69,    0x73,    0x69,    
            0x6f,    0x6e,    0x20,    0x68,    0x69,    0x67,    0x68,    0x70,    0x20,    0x69,    0x6e,    0x74,    0x3b,    0x0a,    0x0a,    0x75,    
            0x6e,    0x69,    0x66,    0x6f,    0x72,    0x6d,    0x20,    0x68,    0x69,    0x67,    0x68,    0x70,    0x20,    0x73,    0x61,    0x6d,    
            0x70,    0x6c,    0x65,    0x72,    0x43,    0x75,    0x62,    0x65,    0x20,    0x74,    0x65,    0x78,    0x5f,    0x73,    0x6d,    0x70,    
            0x3b,    0x0a,    0x0a,    0x6c,    0x61,    0x79,    0x6f,    0x75,    0x74,    0x28,    0x6c,    0x6f,    0x63,    0x61,    0x74,    0x69,    
            0x6f,    0x6e,    0x20,    0x3d,    0x20,    0x30,    0x29,    0x20,    0x6f,    0x75,    0x74,    0x20,    0x68,    0x69,    0x67,    0x68,    
            0x70,    0x20,    0x76,    0x65,    0x63,    0x34,    0x20,    0x66,    0x72,    0x61,    0x67,    0x5f,    0x63,    0x6f,    0x6c,    0x6f,    
            0x72,    0x3b,    0x0a,    0x69,    0x6e,    0x20,    0x68,    0x69,    0x67,    0x68,    0x70,    0x20,    0x76,    0x65,    0x63,    0x33,    
            0x20,    0x75,    0x76,    0x77,    0x3b,    0x0a,    0x0a,    0x76,    0x6f,    0x69,    0x64,    0x20,    0x6d,    0x61,    0x69,    0x6e,    
            0x28,    0x29,    0x0a,    0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x72,    0x61,    0x67,    0x5f,    0x63,    0x6f,    
            0x6c,    0x6f,    0x72,    0x20,    0x3d,    0x20,    0x74,    0x65,    0x78,    0x74,    0x75,    0x72,    0x65,    0x28,    0x74,    0x65,    
            0x78,    0x5f,    0x73,    0x6d,    0x70,    0x2c,    0x20,    0x75,    0x76,    0x77,    0x29,    0x3b,    0x0a,    0x7d,    0x0a,    0x0a,    
            0x00,    
};
    public static unsafe sg_shader_desc cubemap_shader_desc(sg_backend backend) {
        if (backend == SG_BACKEND_GLES3) {
            sg_shader_desc desc = default(sg_shader_desc);
            desc.vertex_func.source = System.Text.Encoding.UTF8.GetString(vs_source_glsl300es);
            desc.vertex_func.entry = "main";
            desc.fragment_func.source = System.Text.Encoding.UTF8.GetString(fs_source_glsl300es);
            desc.fragment_func.entry = "main";
            desc.attrs[0].base_type = SG_SHADERATTRBASETYPE_FLOAT;
            desc.attrs[0].glsl_name = "pos";
            desc.uniform_blocks[0].stage = SG_SHADERSTAGE_VERTEX;
            desc.uniform_blocks[0].layout = SG_UNIFORMLAYOUT_STD140;
            desc.uniform_blocks[0].size = 64;
            desc.uniform_blocks[0].glsl_uniforms[0].type = SG_UNIFORMTYPE_FLOAT4;
            desc.uniform_blocks[0].glsl_uniforms[0].array_count = 4;
            desc.uniform_blocks[0].glsl_uniforms[0].glsl_name = "vs_params";
            desc.views[0].texture.stage = SG_SHADERSTAGE_FRAGMENT;
            desc.views[0].texture.image_type = SG_IMAGETYPE_CUBE;
            desc.views[0].texture.sample_type = SG_IMAGESAMPLETYPE_FLOAT;
            desc.views[0].texture.multisampled = false;
            desc.samplers[0].stage = SG_SHADERSTAGE_FRAGMENT;
            desc.samplers[0].sampler_type = SG_SAMPLERTYPE_FILTERING;
            desc.texture_sampler_pairs[0].stage = SG_SHADERSTAGE_FRAGMENT;
            desc.texture_sampler_pairs[0].view_slot = 0;
            desc.texture_sampler_pairs[0].sampler_slot = 0;
            desc.texture_sampler_pairs[0].glsl_name = "tex_smp";
            desc.label = "cubemap_shader";
            return desc;
        }
        return default(sg_shader_desc);
    }
}

} // namescape 

